version: '3.8'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/user/src/app/
      #- .:/code
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=xtra_time_123
      - POSTGRES_DB=xtra_time_db

volumes:
  postgres_data:

#To persist the data beyond the life of the container we configured a volume.
#This config will bind postgres_data to the "/var/lib/postgresql/data/" directory in the container.

#We also added an environment key to define a name for the default database and set a username and password.