version: 2
jobs:
  build:
    docker:
      - image: xtratime/xtra-time_web:latest
        auth:
          username: xtratime
          password: Benfik@55      
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            python3 manage.py test
      - store_artifacts:
          path: test-reports/
          destination: python_app

#checkout: This command fetches your source code over SSH to the configured path 
#(the working directory, by default).


#restore_cache: This command restores a previously saved cache.


#save_cache: This command generates and saves a cache of a file, multiple files,
#or folders. In our case, we save a cache of the installed Python packages obtained after running pip install ….


#store_artifacts: This command stores logs, binaries, etc. so that
#they are accessible by the app in later runs.